version: '3.8'

services:
  redis:
    image: redis:latest # Official image, typically multi-arch
    platform: linux/arm64
    container_name: redis_benchmark
    ports:
      - "6379:6379"
    # Command to disable persistence for benchmark focus (optional)
    # This makes it faster but data is lost on restart if not explicitly saved.
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  valkey:
    image: valkey/valkey:latest # Official image, typically multi-arch
    platform: linux/arm64
    container_name: valkey_benchmark
    ports:
      - "6380:6379" # Valkey internally listens on 6379, map to host 6380
    # Command to disable persistence for benchmark focus (optional)
    command: valkey-server --save "" --appendonly no
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

networks:
  default:
    driver: bridge